version: '2'
services:
    draft993-app:
        image: draft993
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://draft993-mysql:3306/draft993?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    draft993-mysql:
        extends:
            file: mysql.yml
            service: draft993-mysql
